name: jaguar_mongo
version: 1.3.1
description: Mongo interceptor for jaguar
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_mongo
documentation:

environment:
  sdk: ">=1.20.0 <2.0.0"

dependencies:
  mongo_dart: ^0.3.0
  connection_pool: ">=0.1.2 <0.2.0"
  jaguar: ^1.3.4

dev_dependencies:
  # test: 0.12.15+10
  jaguar_client: ^0.2.0
  jaguar_reflect:
  http:
