name: jaguar_mongo
version: 2.1.1
description: Mongo interceptor for jaguar
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_mongo
documentation:

environment:
  sdk: ">=1.20.0 <2.0.0"

dependencies:
  mongo_dart: ^0.3.2
  conn_pool: ^2.1.1
  jaguar: ^2.1.1

dev_dependencies:
  test: 1.2.0
  jaguar_client: ^2.1.4
  jaguar_reflect: ^2.1.1
