name: jaguar_mysql1
version: 2.2.0
description: A mysql interceptor for Jaguar

authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>
  - Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/db/wiki

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  mysql1:
    git: git://github.com/Hexer10/mysql1_dart.git

  jaguar: ^2.4.30
  conn_pool: ^2.1.8

dev_dependencies:
  jaguar_reflect: ^2.4.5
