name: jaguar_postgres
version: 2.1.1
description: A postgres interceptor for jaguar

authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

dependencies:
  postgres: ^1.0.0-beta.1
  jaguar: ^2.1.8

dev_dependencies:
  jaguar_reflect: ^2.1.1

dependency_overrides:
  jaguar:
    path: ../../jaguar/jaguar
  jaguar_reflect:
    path: ../../jaguar/reflect
  conn_pool:
    path: ../conn_pool
